### ISSUE TITLE
Moving the cursor

### ISSUE THREAD

**Issue by Timendus** [diamant3/chip-walo#1]
> **Issue**
> Up/Down cursor not working in Timendus's chip8-test-suite, idk where's the problem, my chip8 or the test suite

You can't move it using the W/S keys on your PC keyboard? That's weird. Does the keypad test work as expected?

**Comment by diamant3** [comment]
Yes, the keypad test is perfect, thanks, but when it comes to menus, like quirk or the main menu idk, it does not work when I press the S key. When I press the W key and press again until I reach the top, the program silently closes :(

**Comment by Timendus** [comment]
I think I have an idea what could be wrong. As a matter of fact, I'm improving the flags test to add a check for the order in which vF gets set, and I'm guessing that your interpreter is going to fail that new check. See if you can set vF with the flag **after** doing the operation instead of before it. Mainly subtraction in this case. Just an educated guess, let me know if that helps!

Anyhow, thanks for reporting this issue, because it also taught me that my menu relies on the correct implementation of something very iffy, and I'm trying to keep that as flags/quirks agnostic as I can. I'll try to simplify this in the next release.

**Comment by diamant3** [comment]
<img width="378" alt="test" src="https://user-images.githubusercontent.com/71203851/175894240-2949cc88-c118-4f53-81d9-929ec49a77b5.png">

Thanks for the suggestion! Every flag is fine but it's still the same problem, maybe we can leave this open for those who want to fix it

**Comment by Timendus** [comment]
Great to see! But not entirely what I meant 😄

Let me try to rephrase my point. This is your subtraction code:
```c
                // Set register Vx = Vx - Vy, Set register Vf = NOT borrow
                case 0x5:
                    {
                        chip8.register_v[0xF] = false;
                        uint8_t overflow = false;

                        if (chip8.register_v[INSTR_POS_X] >= chip8.register_v[INSTR_POS_Y]) {
                            overflow = true;
                        } else {
                            overflow = false;
                        }
		    	        chip8.register_v[INSTR_POS_X] = chip8.register_v[INSTR_POS_X] - chip8.register_v[INSTR_POS_Y];
			            chip8.register_v[0xF] = overflow;
                        chip8.register_program_counter += 2;
                    }
                break;
```

Now what it we do `v0 -= vF`? You set vF to a boolean in the first part of this code, so we would be "subtracting" a boolean from `v0`, instead of getting the desired result in v0 (and vF set properly with the flag).

A new version of my test tests for this issue too. I'll release that version shortly, and the flags test will have three checkmarks instead of two:

![flags](https://user-images.githubusercontent.com/2649939/175936469-6a6b2276-accf-4306-9f5b-f59381a01d36.png)

**Comment by diamant3** [comment]
thank you so much for pointing out!, i fixed the cursor bug but sorry i didnt get quite right you said, please see my [pr](https://github.com/diamant3/chip-walo/pull/2#issue-1286670647)
